### ISSUE TITLE
Guess who i am im proud of u bro u fr made these i thougth the teacher was joking Good job man:)

### ISSUE THREAD

**Issue by Voidless-ark** [Vumacc/Random-Cat-Discord-Bot#1]
Sup

**Comment by Vumacc** [comment]
Man who are you

**Comment by Vumacc** [comment]
Also sorry for replying so late, I barely go on github

**Comment by Voidless-ark** [comment]
Its me salik from school blud who did u think i was when i said teacher 💀

**Comment by Voidless-ark** [comment]
> Also sorry for replying so late, I barely go on github

And its ok i dont even come here i just come here to see your progress and stuff 😈

**Comment by Vumacc** [comment]
DM me on discord dumbass, don't open an issue if you just want to chat

**Comment by Vumacc** [comment]
Have some manners

**Comment by Voidless-ark** [comment]
G a -
